spring:
  datasource:
    url: jdbc:mysql://47.102.194.232:3306/help2?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: help2
    password: 123456
mail:
  transport: smtp
  host: stmp.qq.com
  port: 465
  userName: 2571402106@qq.com
  password: hhj500235
  enableSSL: true